# Generated by Django 2.2.5 on 2019-09-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=300)),
                ('data_nasc', models.DateField()),
            ],
            options={
                'db_table': 'autores',
            },
        ),
    ]
