# Generated by Django 2.2.5 on 2019-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_livros', '0003_autor_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='livros',
            field=models.ManyToManyField(related_name='livros_autor', to='action_livros.Livro'),
        ),
    ]
