# Generated by Django 2.2.5 on 2019-09-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action_livros', '0004_autor_livros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='livros',
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='action_livros.Editora'),
        ),
    ]
